---
title: "Case Study: Covid19 Analysis"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data

```{r}
library(tidyverse)

raw_covid19_confirmed <- read_csv("https://bit.ly/covid19_confirmed")

raw_covid19_deaths <- read_csv("https://bit.ly/covid19_deaths")

raw_covid19_recovered <- read_csv("https://bit.ly/covid19_recover")
```

## Observe

```{r}
head(raw_covid19_confirmed)


```

## Your Turn - 01


1. Tidy all three data sets 

```{r}
confirmed <- pivot_longer(raw_covid19_confirmed,

cols = 5:ncol(raw_covid19_confirmed),

names_to = "date",

values_to = "count"

)

recovered <- pivot_longer(raw_covid19_recovered,

cols = 5:ncol(raw_covid19_recovered),

names_to = "date",

values_to = "count"

)


deaths <- pivot_longer(raw_covid19_deaths,

cols = 5:ncol(raw_covid19_deaths),

names_to = "date",

values_to = "count"

)

deaths


```

2. Filter out the country by Nepal and remove unused variables.


```{r}
#install.packages("janitor")


raw_confirmed_nepal <- confirmed %>% 
  janitor::clean_names() %>% 
  filter(country_region == "Nepal") %>% 
  select(-province_state, -long, -lat, -country_region)


raw_recovered_nepal <- recovered %>% 
  janitor::clean_names() %>% 
  filter(country_region == "Nepal") %>% 
  select(-province_state, -long, -lat, -country_region)


raw_deaths_nepal <- deaths %>% 
  janitor::clean_names() %>% 
  filter(country_region == "Nepal") %>% 
  select(-province_state, -long, -lat, -country_region)




```


3. Convert date variable into date format.

```{r}

library(lubridate)

confirmed_nepal <- raw_confirmed_nepal %>% 
  mutate(date = mdy(date), 
         type = "confirmed"
         ) 

recovered_nepal <- raw_recovered_nepal %>% 
  mutate(date = mdy(date), 
         type = "recovered"
         ) 

deaths_nepal <- raw_deaths_nepal %>% 
  mutate(date = mdy(date), 
         type = "deaths"
         ) 



```

4. Merge them into a variable named **covid19_nepal**

```{r}

covid19_nepal <- bind_rows(confirmed_nepal, 
                           recovered_nepal, 
                           deaths_nepal)



covid19_nepal

```


## Your Turn - 02

1. Make sure the data set is tidy

2. Try to visualize using **geom_line()**

```{r}

ggplot(covid19_nepal, aes(x = date, y = count, color = type)) +
  geom_line()







```


## Cumulative vs Daily

```{r}

covid19_nepal_daily <- covid19_nepal %>%
  group_by(type) %>%
  mutate(daily_count = count - lag(count, default = 0)) %>%
  ungroup()


covid19_nepal_daily






```

```{r}

ggplot(covid19_nepal_daily, aes(x = date, y = daily_count, color = type)) +
  geom_line()




```

```{r}
covid19_nepal_daily %>% 
ggplot(aes(x = date, y = daily_count, color = type)) +
  geom_line() +
  labs(title = "Covid19-Nepal Cases, 2020 - 2021", 
        caption = "Source: JHUSSE") +
  theme_minimal()
```
 

```{r}

# made by Amar
ggplot(covid19_nepal_daily,
       aes(x=date,color=type))+
  # geom_line(aes(y=count))+
  geom_line(aes(y=daily_count))+
  facet_wrap(~type, nrow=3) +
  labs(title = "COVID-19 cases in Nepal, 2019-2020",
       caption = "Source=JHUSSE")+
  theme_minimal()


```

```{r}

last_30_days <- covid19_nepal_daily %>% 
  filter(date > Sys.Date() - 30, type == "deaths" )

last_30_days

ggplot(last_30_days, aes(x = date, y = daily_count, label = daily_count)) +
  geom_col() +
  geom_text(
    hjust = -0.1,
    angle = 90,
    size = 3
  ) +
  scale_y_continuous(expand = c(.1, .1)) +
  labs(title = "Last 30 days Deaths Cases", 
       caption = "Source: JHUSSE") +
  theme_minimal()

```



```{r}
covid19_nepal_daily %>% 
  filter(date > Sys.Date() - 30, type == "confirmed" ) %>% 
ggplot(aes(x = date, y = daily_count, label = daily_count)) +
  geom_col() +
  geom_text(
    hjust = -0.1,
    angle = 90,
    size = 3
  ) +
  scale_y_continuous(expand = c(.1, .1)) +
  labs(title = "Last 30 days Confirmed Cases", 
       caption = "Source: JHUSSE") +
  theme_minimal()

```
